# Generated by Django 3.0.5 on 2020-04-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
