# Generated by Django 2.0.7 on 2018-07-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('lastName', models.CharField(max_length=255)),
            ],
        ),
    ]
